apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-backend-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link
  template:
    metadata:
      labels:
        app: link
    spec:
      containers:
      - name: link-backend-event
        image: link-backend-event:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: link-backend-event-config
              key: mongodb_uri 